-- Create manager user
CREATE USER manager IDENTIFIED BY manager123;

GRANT CREATE SESSION TO manager;
GRANT CREATE USER, ALTER USER, DROP USER TO manager;
GRANT CREATE TABLE, CREATE ROLE, CREATE PROCEDURE, CREATE TRIGGER TO manager;
GRANT UNLIMITED TABLESPACE TO manager;
GRANT GRANT ANY PRIVILEGE TO manager;
grant create SEQUENCE to manager;
GRANT ADMINISTER DATABASE TRIGGER TO manager;



